import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

# Not really needed honestly
live_config_reload = true

[scrolling]
history = 100000

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Semibold" }
bold = { family = "JetBrainsMono Nerd Font", style = "Extrabold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Semibold Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Extrabold Italic" }
size = 11


[shell]
program = "/home/taxborn/.nix-profile/bin/fish"
